### ISSUE TITLE
Add Continuous Integration with Travis-ci

### ISSUE THREAD

**Issue by TrentBartlem** [ccpgames/EveLogLite#2]
e.g. https://forum.qt.io/topic/50340/installing-qt-5-4-dev-packages-in-travis-ci/15

**Comment by filipppavlov** [comment]
What would be the benefit of doing it?

**Comment by TrentBartlem** [comment]
http://stackoverflow.com/questions/22587148/trying-to-understand-what-travis-ci-does-and-when-it-should-be-used

**Comment by filipppavlov** [comment]
Do you see unit tests in this project? We also have in-house builders for this project so we know when it breaks.
